server:
  port: 8081

spring:
  application:
    name: server-one

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://brasatech.es:8761/eureka}
    healthcheck:
      enabled: false